import type { Metadata } from 'next';
import { Inter, Old_Standard_TT, Cardo, Bodoni_Moda } from 'next/font/google';
import './globals.css';

const old_standard = Old_Standard_TT({ subsets: ['cyrillic'], weight: ['400', '400'] });
const cardo = Cardo({ subsets: ['greek'], weight: ['400', '700'] });
const bodoni_mada = Bodoni_Moda({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Animation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={bodoni_mada.className}>{children}</body>
    </html>
  );
}
